#metadata((
  title: "Reinforcement Learning Quick Reference Notes",
  published: "2026-09-20",
  description: "赵世钰【强化学习的数学原理】重点知识整理",
  tags: ("人工智能", "强化学习"),
  category: "学习笔记",
  draft: true,
))<frontmatter>

#html.elem("p", attrs: (style: "margin-top: -1em;")) 

== Basic Concepts
- *State* (状态) : the status of the *agent* (智能体) with respect to the *environment* (环境) .
 - *State space* (状态空间) : the set of all states $S={s_i}$.
- *Action* (动作) .
 - *Action space* (动作空间) of a state : $A(s_i)={a_i}$ .
- *State transition* (状态转移) : deterministic (确定的) or stochastic (随机的) .
- *Policy* (策略) tells the agent what actions to take at a state, deterministic or stochastic.
- *Reward* (奖励) : a real number we get after taking an action.
- *Trajectory* (轨迹) : a state-action-reward chain.
 - *Episode* (回合) : a finite trajectory stopping at a terminal state.
 - Treat episodic and continuing tasks in a unified way by converting episodic tasks to continuing tasks: treat the target state as a special absorbing state or a normal state with a reward.
 - The *return* (回报) of a trajectory is the sum of all the rewards collected along the trajectory.
 - *Discounted return* (折扣回报) : return with a *discounted factor* (折扣因子) .
- *Markov decision process* (*MDP*, 马尔可夫决策过程) :
 - Sets: $S, A(s), R(s,a)$.
 - Probability distribution: $p(s'|s,a), p(r|s,a)$.
 - Policy: $pi(a|s)$.
 - Markov property.

== Bellman Equation
- Purpose: calculate the value for *policy evaluation*. #v(0.3em)
- *State value* (状态价值) : $v_pi (s)=EE(G_t|S_t=s)$, where $G_t=R_(t+1)+gamma R_(t+2)+gamma^2 R_(t+3)+...$ #v(0.3em)
- Two forms of *Bellman equation* (贝尔曼公式) :#v(-0.2em)
 - \ #v(-1.5em) $v_pi (s) &=EE(R_(t+1)|S_t=s)+gamma EE(G_(t+1)|S_t=s)\ &=sum_a pi(a|s) (sum_r p(r|s,a)r+gamma sum_s' p(s'|s,a)v_pi (s')) quad"(elementwise form)"$
 - \ #v(-1.5em) $v_pi (s_i) &= r_pi (s_i)+gamma sum_(s_j) p_pi (s_j|s_i) v_pi (s_j) \ => bold(v)_pi&=bold(r)_pi +gamma bold(P)_pi bold(v)_pi quad"(matrix-vector form)"$ #v(0.3em)
- *Action value* (动作价值) : $q_pi (s,a)=EE(G_t|S_t=s,A_t=a)$ #v(-0.2em)
 - \ #v(-1.5em) $v_pi (s)=sum_a pi(a|s) q_pi (s,a) \ q_pi (s,a)=sum_r p(r|s,a)r+gamma sum_s' p(s'|s,a)v_pi (s')$ #v(0em)
- Solve the Bellman Equation:
 - Closed-form solution: $bold(v)_pi =(bold(I)-gamma bold(P)_pi)^(-1) bold(r)_pi$
 - Iterative solution: $bold(v)_(k+1)=bold(r)_pi +gamma bold(P)_pi bold(v)_k$ ,$quad lim_(k->oo) bold(v)_k=bold(v)_pi$ #v(0.3em)

== Bellman Optimality Equation
- *Optimal policy* (最优策略) : $pi^*$ such that $ v_(pi^*) (s)>=v_pi (s) space forall s space forall pi$.
- *Bellman Optimality Equation* (*BOE*, 贝尔曼最优公式) : $v^*(s)=max_pi sum_a pi(a|s) q^* (s,a)$, or $bold(v)^*=max_pi (bold(r)_pi +gamma bold(P)_pi bold(v)^*)$.
- *Contraction mapping theorem* (压缩映射定理) : If $f$ is a *contraction mapping*, that is, $||f(x_1)-f(x_2)||<=gamma||x_1-x_2||$ where $gamma in (0,1)$, then the *fixed point* of $f$ exists and is unique, and the sequence generated by the *iteration* $x_(k+1)=f(x_k)$ *converges* to that fixed point.
- $bold(v)^*=f(bold(v)^*)=max_pi (bold(r)_pi +gamma bold(P)_pi bold(v)^*)$ is a contraction mapping, hence, the optimal policy can be determined by iteration.
- An optimal policy $pi^*$ is a deterministic greedy policy, that is, $pi^*(s)=arg max_a q^*(s,a)$.

== Value Iteration and Policy Iteration Algorithms

- *Value iteration algorithm* (值迭代算法) : Start from $bold(v)_0$, $bold(v)_(k+1)=f(bold(v)_k)=max_pi (bold(r)_pi +gamma bold(P)_pi bold(v)_k)$, which can be decomposed into two steps:
 - Step 1: policy update (PU) . $pi_(k+1)=arg max_pi (bold(r)_pi +gamma bold(P)_pi bold(v)_k)$ where $bold(v)_k$ is given. $pi_(k+1)$ is a *greedy policy* (贪心策略) .
 - Step 2: value update (VU)  . $bold(v)_(k+1)=bold(r)_(pi_(k+1)) +gamma bold(P)_(pi_(k+1)) bold(v)_k$. This update resembles the Bellman equation in form, but is not identical to it. $bold(v)$ here does not represent the state value either.
 - In elementwise form, the policy simply selects the optimal action for each state, and $v_(k+1)$ is the maximum $q_k$.
- *Policy iteration algorithm* (策略迭代算法) : Start from $pi_0$,
 - Step 1: policy evaluation (PE). $bold(v)_(pi_k)=bold(r)_(pi_k) +gamma bold(P)_(pi_k) bold(v)_(pi_k)$. Calculate the state value of $pi_k$ via iterative methods.
 - Step 2: policy improvement (PI). $pi_(k+1)=arg max_pi (bold(r)_pi +gamma bold(P)_pi bold(v)_k)$.
- *Truncated policy iteration algorithm* (截断策略迭代算法) : When solving the Bellman equation in the PE step via iterative methods, only $j$ iterations are performed. Value iteration is equivalent to $j=1$, while the theoretical policy iteration is equivalent to $j=oo$.

== Monte Carlo Learning

- Unlike *model-based methods* (有模型方法) , *model-free methods* (无模型方法) need to adopt the idea of *Monte Carlo* (*MC*, 蒙特卡洛) *simulation* : estimating probabilities from frequencies.
- *MC Basic algorithm*: PE estimates the action value $q_(pi_k) (s,a)$ by averaging sufficiently many samples $g(s,a)$ of the discounted return $G_t$, while PI remains unchanged.
- *MC Exploring Starts algorithm*: a sample-efficient variant of MC Basic algorithm.
 - A single episode is used to estimate multiple $q_(pi_k) (s,a)$, via the *first-visit method* or the *every-visit method*.
 - A single episode's return is used to directly approximate the action value, so that the policy is improved episode-by-episode.
 - Exploring starts: collect episodes starting from every state-action pair, which is difficult to achieve in practice.
 - *Generalized policy iteration* (*GPI*, 广义策略迭代) : the general idea of switching between PE and PI processes, where the value is estimated roughly.
- *MC Epsilon-Greedy algorithm*: MC without exploring starts.
 - *Soft policy*: the probability to take any action is positive.
 - *$epsilon$-greedy policy*: $pi(a|s)$ assigns probability $epsilon/abs(A(s))$ to every action other than the greedy action, where $epsilon in [0,1]$. It strikes a balance between *exploitation and exploration* (探索与利用). But it is not optimal in general.

== Stochastic Approximation and Stochastic Gradient Descent
- *Stochastic approximation* (*SA*, 随机近似) : a broad calss of stochastic iterative algorithms solving root fiding or optimization problems. It does not require to know the expression of the objective function nor its derivative.
- *Robbins-Monro* (*RM*) *algorithm*: $w_(k+1)=w_k-a_k tilde(g)(w_k,eta_k)$, where the observation noise $eta$ is a random variable, $tilde(g)(w_k,eta_k)=g(w_k)+eta_k$ is the $k$th noisy observation. Then $w_k$ converges with probability 1 (w.p.1) to the root $w^*$ satisfying $g(w^*)=0$, where the function $g(w)$ is a black box.
 - Three conditions:
  - The gradient $gradient_w g(w)$ is positive and bounded.
  - $sum_(k=1)^oo a_k=oo$ and $sum_(k=1)^oo a_k^2<oo$, which guarantees that $a_k$ converges to zero but not too fast. One typical sequence is $a_k=1/k$. $a_k$ is often selected as a sufficiently small constant in practice. 
  - $EE(eta_k|H_k)=0$ and $EE(eta_k^2|H_k)<oo$, where $H_k={w_k,w_(k-1),...}$.
 - Philosophy: Without model, we need data!
 - Apply to mean estimation: $w_(k+1)=w_k+alpha_k (x_k-w_k)$, where in this case $g(w)=w-E(X)$, $eta=E(X)-x$, $tilde(g)(w,eta)=g(w)+eta=w-x$.
- *Stochastic gradient descent* : aim to solve the optimization problem $min_w J(w)=EE(f(w,X))$.
 - *Gradient descent* (*GD*, 梯度下降) : $w_(k+1)=w_k-alpha_k gradient_w EE(f(w_k,X))=w_k-alpha_k EE(gradient_w f(w_k,X))$, where $alpha_k$ is the learning rate.
 - *Batch gradient descent* (*BGD*, 批量梯度下降) : $w_(k+1)=w_k-alpha_k 1/n sum_(i=1)^n gradient_w f(w_k,X_i)$, where $n$ is the batch size.
 - *Mini-batch gradient descent* (*MBGD*, 小批量梯度下降) : $w_(k+1)=w_k-alpha_k 1/m sum_(j in I_k) gradient_w f(w_k,X_j)$, where $I_k$ is a uniformly random subset of ${1,2,...,n}$ with the size as $abs(I_k)=m$.
 - *Stochastic gradient descent* (*SGD*, 随机梯度下降) : $w_(k+1)=w_k-alpha_k gradient_w f(w_k,x_k)$, where the true gradient is replaced by the stochastic gradient $gradient_w f(w_k,x_k)$, which is an unbiased estimate of the true gradient. It is a special case of RM algorithm with $g(w)=gradient_w J(w)$, $eta=gradient_w f(w,x)-gradient_w J(w)$, and $tilde(g)(w,eta)=g(w)+eta=gradient_w f(w,x)$.
 - SGD convergence conditions: $gradient_w^2 f(w,X)$ is positive and bounded, $sum_(k=1)^oo a_k=oo$ and $sum_(k=1)^oo a_k^2<oo$, ${x_k}_(k=1)^oo$ is *identically and independently distributed* (*iid*, 独立同分布) .