// 本文件由 src/plugins/music-metadata.mjs 在构建时自动生成，请勿手动编辑。
// 修改 src/config.ts 中的 localPlaylist 或更换音频文件后，重新构建即可自动更新。
import type { Song } from "../../../types/music";

export const musicPlaylist: Song[] = [
	{
		id: 1,
		title: "再见，朋友 (Farewell, My Friend!)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/再见，朋友 (Farewell, My Friend!).mp3",
		duration: 266,
	},
	{
		id: 2,
		title: "向尖顶攀升的俯冲 (Ascending Dive Towards the Pyramidion)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/向尖顶攀升的俯冲 (Ascending Dive Towards the Pyramidion).mp3",
		duration: 332,
	},
	{
		id: 3,
		title: "向着地图上的空白 (Towards the Blanks on the Map)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/向着地图上的空白 (Towards the Blanks on the Map).mp3",
		duration: 193,
	},
	{
		id: 4,
		title: "回忆 (Reminiscence)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/回忆 (Reminiscence).mp3",
		duration: 189,
	},
	{
		id: 5,
		title: "天空的指环 (Ring of the Sky)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/天空的指环 (Ring of the Sky).mp3",
		duration: 325,
	},
	{
		id: 6,
		title: "幻想乐园 (Welcome to Fantasyland!)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/幻想乐园 (Welcome to Fantasyland!).mp3",
		duration: 183,
	},
	{
		id: 7,
		title: "新的旅程 (A New Journey)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/新的旅程 (A New Journey).mp3",
		duration: 115,
	},
	{
		id: 8,
		title: "永夜之城的轮舞 (Circle Dance of the Evernight Castle)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/永夜之城的轮舞 (Circle Dance of the Evernight Castle).mp3",
		duration: 374,
	},
	{
		id: 9,
		title: "海与月的女儿 (Daughter of the Sea and the Moon)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/海与月的女儿 (Daughter of the Sea and the Moon).mp3",
		duration: 386,
	},
	{
		id: 10,
		title: "花与罪的无限回廊 (Infinite Cloister of Flowers and Sins)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/花与罪的无限回廊 (Infinite Cloister of Flowers and Sins).mp3",
		duration: 387,
	},
	{
		id: 11,
		title: "雪融之境的繁光 (Flourishing Lights of the Snowmelt Realm)",
		artist: "陈致逸",
		cover: "music/cover/幻想乐园 Fantasyland.jpg",
		url: "music/url/雪融之境的繁光 (Flourishing Lights of the Snowmelt Realm).mp3",
		duration: 421,
	},
];
